apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-cost-secret
  namespace: demo
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: awssecretmanager
    kind: ClusterSecretStore
  target:
    name: aws-cost-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: dev/aws/cost